server:
  port: 8080

my.path: /**
my.uri: http://localhost:8081/

spring: 
    codec: 
      max-in-memory-size: 10000MB

#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: employeeModule
#        uri: http://localhost:8888/
#        predicates:
#        - Path=/aaaaaawebsamples.countryinfo/**
#        filters:
#        - ReadRequestBodyFilter
#        - LoggingFilter
#        - AddRequestHeader=myvar, 1
#        - RemoveRequestHeader=aaa
#        - AddHeaderFilter
#        - DinamicRouteFilter
#        - ChangeDestinationUri
#        - AddResponseHeader=first-response, first-response-header
#        
#        
#      - id: consumerModule
#        uri: http://localhost:8082/
#        predicates:
#        - Path=/consumer/**
#        filters:
#        - AddRequestHeader=second-request, second-request-header
#        - AddResponseHeader=second-response, second-response-header
#        
#        
#        
#      - id: myws
#        order: -1
#        uri: http://webservices.oorsprong.org/
#        predicates:
#        - Path=/websamples.countryinfoaaaaaaaaaaaaaaaaaaaaaa/**
#        filters:
#         - ChangeResponseFilter
#         - DinamicRouteFilter
#         - ChangeDestinationUri
##        - AuthorizationFilter